### ISSUE TITLE
SLIM integration: Infusion of Lab-approved documentation and templating standards

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/VICAR#1]
**Checked for duplicates**

Yes -- New feature, new files.

**Alternatives considered**

Yes - This is a Lap-approved and suggested addition to all MIPL repositories.

**Related problems**

Many repos don't provide comprehensive documentation and/or are missing key areas of standardized documentation focus. This feature adds standardized documentation per Lab-approved standards.

**Describe the feature request**

A number of template and documentation files are being added to the repository in support of the SLIM project. These files are suggested by MGSS and will serve to promote cohesion between MIPL products. The files are being provided tailored to the current repository with minimal integration assistance and upkeep requested of CogE and/or developers.

See commit history in the [slim_infusion branch](https://github.jpl.nasa.gov/MIPL/VICAR/tree/slim_infusion) for added files.

**Comment by sharimayer** [comment]
This proposal should be bounced off of Bob Deen. He is the one to determine if this would be useful for Vicar Open Source.

**Comment by rgdeen** [comment]
I'm afraid I'm lacking any kind of context here.  When would these be used, and by whom?  Is this intended to replace the current JIRA system for VICAR?  How do you handle DARs... simple things the developer finds like typos or whatever that are not motived directly by users?  Probably need a meeting to discuss.

**Comment by riverma** [comment]
Hi @rgdeen - sorry let me add some context: I was assuming bug reports and new feature requests from users were (or could) be solicited from the GitHub VICAR repository. Do you all have another mechanism to triage user requests? If not - these issue templates can help standardize the ticketing process with respect to the public open source community.

**Comment by rgdeen** [comment]
@riverma is there some way I can see the full forms?  You have an excerpt above for bugs and feature requests but it doesn't show all fields.

Sorry for the delay, was on vacation for 3 weeks

**Comment by riverma** [comment]
Hi @rgdeen - sorry for my own late reply, please see the below:
- Bug Reports ([example](https://github.com/riverma/terraformly/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+), [source](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/bug_report.yml))
- Feature Requests ([example](https://github.com/riverma/terraformly/issues/new?assignees=&labels=enhancement&template=feature_request.yml&title=%5BNew+Feature%5D%3A+), [source](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/feature_request.yml))

You can take a look at our write-up on how to use these form templates in your repository: https://nasa-ammos.github.io/slim/documentation/starter-kits/#github-issues-forms

**Comment by jpl-jengelke** [comment]
Complete
